"""add paciente_nombre to cirugias

Revision ID: 6d44f14b1873
Revises: ade3cd18b4b3
Create Date: 2026-01-13 12:36:49.912746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d44f14b1873'
down_revision = 'ade3cd18b4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cirugias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paciente_nombre', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cirugias', schema=None) as batch_op:
        batch_op.drop_column('paciente_nombre')

    # ### end Alembic commands ###
